import React,{useEffect,useMemo,useState}from'react';import WORDS from'./words';
const CATS=['Meetings','Projects','Engineering','Manufacturing','Quality'];const mix=a=>[...a].sort(()=>Math.random()-.5);
const load=()=>{try{return JSON.parse(localStorage.getItem('tg-pwa'))||{ok:0,bad:0,errors:{}}}catch{return{ok:0,bad:0,errors:{}}}};
export default function App(){const[selectedCats,setSelectedCats]=useState(CATS);const[direction,setDirection]=useState('DE_EN');const[mode,setMode]=useState('quiz');const[stats,setStats]=useState(load);const[current,setCurrent]=useState(WORDS[0]);const[options,setOptions]=useState([]);const[picked,setPicked]=useState(null);const[flipped,setFlipped]=useState(false);const[install,setInstall]=useState(null);
useEffect(()=>localStorage.setItem('tg-pwa',JSON.stringify(stats)),[stats]);useEffect(()=>{const h=e=>{e.preventDefault();setInstall(e)};window.addEventListener('beforeinstallprompt',h);return()=>window.removeEventListener('beforeinstallprompt',h)},[]);
const filtered=useMemo(()=>WORDS.filter(w=>selectedCats.includes(w.cat)),[selectedCats]);const errors=useMemo(()=>Object.keys(stats.errors).map(k=>WORDS.find(w=>w.de===k)).filter(Boolean),[stats]);
const target=direction.endsWith('_EN')?'en':direction.endsWith('_PT')?'pt':'de';const source=direction.startsWith('DE_')?'de':direction.startsWith('EN_')?'en':'pt';const answer=current[target],prompt=current[source];
function newQuestion(nextMode=mode,poolOverride){const base=poolOverride||(nextMode==='review'&&errors.length?errors:filtered);const pool=base.length?base:WORDS;const w=pool[Math.floor(Math.random()*pool.length)];const vals=[w[target],...mix(WORDS.filter(x=>x.de!==w.de).map(x=>x[target])).slice(0,3)];setCurrent(w);setOptions(mix([...new Set(vals)]));setPicked(null);setFlipped(false)}
useEffect(()=>newQuestion(mode,filtered),[direction,selectedCats]);
function toggle(c){setSelectedCats(s=>s.includes(c)?(s.length===1?s:s.filter(x=>x!==c)):[...s,c])}function choose(v){if(picked)return;setPicked(v);if(v===answer)setStats(s=>{const e={...s.errors};if(e[current.de]){e[current.de]--;if(e[current.de]<=0)delete e[current.de]}return{...s,ok:s.ok+1,errors:e}});else setStats(s=>({...s,bad:s.bad+1,errors:{...s.errors,[current.de]:(s.errors[current.de]||0)+1}}))}
function setM(m){setMode(m);newQuestion(m)}const total=stats.ok+stats.bad,accuracy=total?Math.round(stats.ok/total*100):0;
return <><header><div><small>TECHNICAL GERMAN PWA</small><h1>Engineering Vocabulary Trainer</h1><p>500 terms and workplace phrases • English + Portuguese • offline</p></div>{install&&<button className="gold" onClick={()=>install.prompt()}>Install app</button>}</header><main><nav><button className={mode==='quiz'?'active':''}onClick={()=>setM('quiz')}>Quiz</button><button className={mode==='review'?'active':''}onClick={()=>setM('review')}>Review errors ({errors.length})</button><button className={mode==='flash'?'active':''}onClick={()=>setM('flash')}>Flashcards</button></nav><section className="filters"><strong>Categories</strong><div>{CATS.map(c=><button className={selectedCats.includes(c)?'selected':''}onClick={()=>toggle(c)}>{c}</button>)}</div><select className="direction" value={direction} onChange={e=>setDirection(e.target.value)}><option value="DE_EN">German → English</option><option value="EN_DE">English → German</option><option value="DE_PT">Alemão → Português</option><option value="PT_DE">Português → Alemão</option></select></section><div className="layout"><section className="card quiz"><div className="eyebrow">{mode==='review'?'ERROR REVIEW':mode==='flash'?'FLASHCARD':'QUIZ'} • {current.cat}</div>{mode==='review'&&!errors.length?<div className="empty"><h2>No errors to review</h2><p>Incorrect answers are added here automatically.</p><button onClick={()=>setM('quiz')}>Start quiz</button></div>:mode==='flash'?<div className="flash"onClick={()=>setFlipped(!flipped)}><span>{flipped?'ANSWER • CLICK TO FLIP':'QUESTION • CLICK TO FLIP'}</span><h2>{flipped?answer:prompt}</h2></div>:<><h2>{prompt}</h2><div className="options">{options.map(o=><button onClick={()=>choose(o)}className={picked?(o===answer?'correct':o===picked?'wrong':'muted'):''}>{o}</button>)}</div>{picked&&<div className="feedback"><b>{picked===answer?'Correct!':'Correct answer: '+answer}</b><button onClick={()=>newQuestion()}>Next word</button></div>}</section><aside className="card"><h3>Your progress</h3><div className="meter"><i style={{width:accuracy+'%'}}/></div><div className="score"><div><b>{accuracy}%</b><span>Accuracy</span></div><div><b>{stats.ok}</b><span>Correct</span></div><div><b>{stats.bad}</b><span>Incorrect</span></div><div><b>{errors.length}</b><span>To review</span></div></div><button className="reset"onClick={()=>setStats({ok:0,bad:0,errors:{}})}>Reset progress</button></aside></div></main></>}
